# apps-definitions/neltharion/argocd.app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"        # avant tout le reste
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jbwittner/homelab_gitops
    targetRevision: main
    path: infra/argocd                         # le MÊME dossier que ton apply manuel
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false                             # ⚠️ prune désactivé — voir explication
    syncOptions:
      - ServerSideApply=true                   # ⚠️ doit matcher ton apply manuel
      - RespectIgnoreDifferences=true