apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: 39.0.9
      chart: traefik
      helm:
        valueFiles:
          - $infra-repo/infra/traefik/values.yaml
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: infra/traefik
