apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $src/neltharion/infra/cert-manager/values.yaml
    - repoURL: https://github.com/jbwittner/homelab_gitops.git
      targetRevision: main
      ref: src
      path: neltharion/infra/cert-manager                              # ClusterIssuer + token Cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
