---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCvp+Sa4AHcyswmAirj0IcjUpggHHjzI/SZIliz+XeLcOnQEY4KpyEGTA9zKr0Y0ZRlP3L/khpal7f7O59vcipYqENV1BpVwp6LYtFUp3FVFWpKr9TDbUhcBlCsKV3dw+mTMYFuyFGN0epy3VnAbYkdqHIh7yArVNtv28LbH0cEv05mJLywlI55pG0mDJVnoMipFCR7YFNfllo0lPnRZyKOiq6mRBpyz6/yjjbL7A/F8NUvj1WcWIe6mw21nZPFedC7rZqStl7KuAD0JHwJU7L8xazjmsghcfvcm1CfSRk18MnoH/Rto53hec/4X1WJPbj/flE2Zn/cObzanBlj5qi7fqmI4kulhj/XaL4XkcHeD9uo8Nfh4mXsn4AIS2D+qPRGKoiKz+VycMr5y0gaO79SkftgbBr+QmxwjPc74IQdFWUrq8UcXWm2ch4ldB+fs9tlr1D0dVf2ho73EIjo117+fASTGQ0rAZmS+PwZ/34cCnswZCc/EAfzj5qu7a4j/NaZFGdpYmmnUYEa5Ziv/AxTwSGrP9d0+2c0KJVRVYA/ApdW+hxqIUJKdbOKuOIAEYSkGzFPPyi8gK7GKJlin3VV1NauFQExHoRrKYsc0kszJD08XtkWRpG/MZj/BVMKEO0KnFrXce4L7CAjwAisju7XOlf+AsoXgMLuKfanxW4KoF8p3G4KaHgSQ3Oow8nf9dtOy8Idn3rIiUQVgNIaFMmwhmlG8iUUsSRRjXo9pcOKJq3uYTGoOvWm7WfY2/ayBl4wJxvGTg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
