---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDOJfIQdPBjM168vMq0/5XdbIYnV/qcuGKuwutCzbra/2qI2iaR4tj/fSiO/rzhbkH1Fou0240u5mftPEjleGhejtsXF4dzE2K48CLsx6eeLbeB/2UZiMCcgYqcY5XVq/nrSQ0UCj7GQ3O/A027BWXMKSyCqo8f/AKKymAjUPX8XjId6NvJiCZpUk2I5AptUDVDFEPlmaXjT3CTqKkBKizL6qctwcAjNJ2wRLlTdCqRVyX4ZCUJafNmVFrMUBhK6f+BaZ1dqilZ9Q6SCj+dKmZPHEGDswVZK/eZA/97HpcSfaTp2shb+3IPYYZytzJ7eaCLEutZ8koRkBy/VyWLU7wwasULSjUUuSlULa9jmlNoQE1Gt0vTi6Qlz8TwWk/u5ltOv95avpoIyfjXSodugO/AkZy5MQGpFIC1VEjy/tUZhr1AhZkj59cYQuSXXxAHZ9B+S48k/WgfbGeupy/u7AF4e8qHguVEf+ilmvR2uCDVf4TLpdN2fw7fBUnh5fh2l21PnRt+5/0q8k+9SQpgAbzdgF/W5UoJKG4s17qPtS0YH8guQAkmUhx1WV7Xa1BKs9f+aqi6HrnXDSjNFaSc7DmvsS03kQqdCr1MzGuuS0VW1WAaAzsiSCxS3M/64nH76t0Ky6Wf8IiDijIJBXeOEITugFULganyqyWi+v8g2CeLXXTysFw6FKfSr4hAAwF7QBMpjEsMXWYhCRVk141BBAQuj/5lwjIhrxPjj2Nl2wpphVOQtnXlcfRKq7tCk5wYR4pFjtIXsg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
