---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgABM+bU7ePp2q4djOlU9Djv5goqESm7qBAH9IV3x+9dUMIl4p4iGq7FCdPEswQDAWWI6sUZR7tdkkRlU9bDs7cGThHMUsmkXLkwTKuzyr9ZyL3KdD6Fd698fxz8DsmDHfldb7N5YL7UGnJKBUXD9DgfV3BRj4S6txpplijFqlMZ3eaXJfAfkmPXp8JrLtMlnFE19214NwuEPc3B6CHm+fC0634EDhGUGW7IMtSEHGvV+0opIszmHdHIqm5VrCFB4RfwIrzI4dVfLfwDPl1BqlsE4fd6t5umhvOqkPXaAdoHSZleaZejc3+/BoG1mS5qOK3F1r9Av98in0rRX9IrfhSMrMuUYqC/g0OZ5A0nYjztM35luK6rwgj66+75Wmp+5f7/l6XCc0GuJJ2fC9YbZW6u/Wer7QGwTQp/UWLueYqq3WOI+FyJy6s1/zoVIElP0DV33eKiD9lugf/m86CXYliqvu8YHoMDOMNsXTy2MV/Y4vol+mWa63SlspBX/ZMugnnC6GVwS5c8RFhgnhFuCid7q3jNBGk6O9rxM/qYJUmoMgPUC9cqrBVRj0GaEPSvKmoWEq/jLhRJql2xbpN97je9hyLMzb/+33xvThhNpqvZv+rXCqr87T+p0ynnU/7qPo+yhvq9hBIAdSFWIFjqV37JLK0o5Eco8QkaEpvduppSz1ykSo2H6QL3YJl2MaaxBp351PmtesoF2UlGVI5bxt1uWAPce00hDmvuY8ckuh+YTVPjEoORfuZml+q2up5Ipf18zTBAmw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
