---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgBkA6EQlM/f3J4AAUiOZPibPzv2+CMl9tk3cwXgehdIP+qxUhdDaL4hNz9qSKTNO/+e+BJgOSc7xrHXL/c3PIsPGT2BDTIi/FN+E/vvZVAUkCuqMefktWTXhkFuy7cyudO4Fw7rIauvQiyJkWLjiWUumw7tZeaDScRkzCYyYpRGuGccjKqgjVZvwjF+04I2QbwGTrx2mcvr78ql+I+U1A6Qy8v/luFtIRtaavPvra9GG73P5lf1R0tJwKwH3AxSC4w3kRXcZSzB/ZO9bPpUtiKN+mxAoueCuvO6RJMEoSco5aCvnWaRbf8zETw0iJ+lzGemD76LNmDo0/Yss9X4qREoheRScouqcItAHwuvsqTJlzpmceNBNQPE1EEhEynqmq9tIuwmu8BF2f+gr2tkvRZypSHBe/ZS9sCpvFJMCUExXa6CfwSR9ezNQBCQnv55wGw04VtiqSHAv4FUORy9Xx1UhcM7eialvrE+I7dthQQI0qrk9GxqTqtEyJ+ISQQHkgCF01CzBn2UjpITM0L+t9ACobGsq1URjzUI+4GbJxiZOqgjQBj/lLA2iW7Ssen8zZT5f0PGTxmIVrXmYMT5YStAtuvCSIBd09IziJpa4DNFIS65odiCr57rmJ0z88SSpcU/PvmuEgA+FoQ/vCJo0Kv8PcANvPp8RadEfoAijOAbwqKnPTOgo/1YgaE9D3WPgZ2rrrLFGF+WmBpbLp46Vrn2/5Jsx5kH18DR09fGa4n3dg7wTLc2U9HtFsEvxYuUDDo=
  template:
    metadata:
      name: argocd-oidc
      namespace: argocd
      labels:
        # OBLIGATOIRE : sans ce label, ArgoCD ignore le secret référencé par
        # $argocd-oidc:client-secret → client_secret vide → invalid_client.
        app.kubernetes.io/part-of: argocd
    type: Opaque
