---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    grafana-apikey: AgBGP4gAjUFlDAO2CbLOmscgXc/la4ta1XbPXjCvnmEJZD/bCr0UmMLlnEu9Se6SnmgQANyfbJFzPCQiTpZRziCAShU/ZSRPnm4GMqSDTTP2lCdsVXo0VhRPU0nyG8hDYPglk92HXGkoFyCTGmSy/+o8HDszWUqFyR1hjgIpPuqS2/ofCnfFY9lRW0ZXjeyW1HDgWNUtzQyy1RFeSwkQDzLiA0OqSdl8Q2mdqxYX2E3K7UYwTDFGe79zw3epG56encDNN0B61nQvJ5SkrDp6KKr83AvjG0VqyrEqgxiL4cmkqfs04D0y0NbAeEW/8zKVDsRJwYzn8Rfx779xEL8XBRaZT8pKZwbYz9EKDQlpg+nDR22Y01ewqd9ZpNT88lhqIE+eWXQ5XD2lpd5KQeMeG5qhGRtqtolqORNNYHDFy2Z91AwkNiIxgm/v7zjmVU4jU4dgHlfX1wjs3vr9/pdYTIvxUdGIAJa+xAqg8xswUsMDRzwqo5SIstZEfVU8SVAXy7hDlsYF/gIi7vmSiClHkVMep8JPh/92B2h/bukzvsPWj4dAFYQwdSkClMNaZ81c9tPn/90L1VzdsybERC+8cPLf/Kk6QQUAUi5OY02qCLqh037441wdkgbSBJ6DwwQmoAiek+a8mDVkb5L/B902wCWlcHTZf/zKHnTy02DuvnQL9TY07yjBwTkFMOkt2sixLycASDxXm6EnSfamUhh81I9wRpnm9McJ03dfKA5HxlIrliz+pAz0P1vlUzH3+ftx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
