apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openebs-lvm-localpv-node
  namespace: openebs
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - openebs
  selector:
    matchLabels:
      openebs.io/component-name: openebs-lvm-node
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s