---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbao-snapshot-gcs
  namespace: openbao
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC5TaunyQTH6/iv0ssNrT8tVuMIGNjzVxvc5T4eVdZuNl46r2/rwXvOTxyEVmEEAL44NJLNgctj+qZWymZuaJjMTU/bRY+s+pU1kx9NmQHY8vdI3KI2UNRoD9war7wdZ2aawpyuXYUlCBnpC9NAoN53MHmcN/TlTl19s9IwTynN0aq3dY8xwWABIicmvkEnqe7C+zQTT6SLSVwd7puPa2UWvApSBEj2PNRi8zSS8ldjaU10bHv3MwddKY5miWDLhXYDvToLhQpuzcI/5qH9hlQTlrTGUYv1MQWicbverstYkoWB93LdKvc0sHaiY/DoM395YELlK68EvvjPrBLNSOmKmVjQi+GS5hZHuJKbFcgIs1OhoKlt/hIW08YQZL5q6QdbWFTqLXMqp2Myurmqaqg/XCL3E8KQTh9WptdwNSBUPgAYE1Gah+ybLjLm9yqnjQsq5pINB1qOid1NizLHWt8F2qjTg60PhpPy5wvlhrFGMyMcAd0Od1PccaDyZqzVsFTWuTeH7uqdXQMfxrL0tVJj75m0WblUNjSsDur8BueQEsRHjw1ayR/ZkYmfRFgfmBBxDg/DwkJRI0X71BdJKYr4T07ah7fTsE69QWZjxftsWz6VDEy5ZoH1ziKkukNUgql807QsU8rLS8wPCuFLVdpvOTgjqGNcTz1KSntn/loHIVMcAQFhSTuvxQf8VhO8mModoVM1r6Z4vgsXaa65I43WrI/OLtafn1LqOQCPO3Lqcj3KmdfCP7Er1hk+R26YFu+FeuBywM3XRpzKB3lp
    AWS_SECRET_ACCESS_KEY: AgCj9jBGWT/uO+6W+L/gtUY44VxX/ohWMIZZ0Eb8Lwx2eszc/NG3K6lGGuD1qx+ipetO4SDU5B1MYEC/Xqvgxcvr7SZ/HerDFJyl2dXt6JF1P9QUIqKkfMmVFf4veKW4ntxkMbGTv61uSdIvsOcVIV5+rHq16H5BYRGR/I6RSfJdDC6/v09kQ24Ntc+oWr8hBGJBmsECqoNMupPx2WoWU8JPjCSY2560EkKL3i2+mg1Zzet4wRnpEpuhxLr9YjurrFu3zvuW7hTmR3v9bFV+qlZW7VL/tGIX820lboM3kCA3fVIsv6DesVAwGpUx686MWP9TvvHqIYz9f1Yp1aWvFJEpBuSQE6ao3b71vrs7la9Q71IskoQJ+pJDxZiEQ0T83kbUaf7pGPFJjccO5B7Ct4Jii4J2LS2HfUdTJLE2ee/gysqybZd1YDMeTyBFC6tOUB+JqChxv7XZHmvqPHXoIp9ZrtetDRWtGWApgleGZkSMe9XHLM+HiUSLemnCBpOkg//clPObill4qab4jvLW6QyOqLEbkGwieL7AjwNeMdhE6mPP8q7hW2qOZckymm+QpZ9bWIVVp5/hEIFtuAj4ciq7IK8v0ZviVtXowl6ZWW0CzkwBnyJRMVFnOQJV0aDxTt2CVXa5vtCXMY6Dg8emTmMGYFoDt94XTwJMv8gA++RLVOcwxSsILHjw6hVKAkT4ZAas1Aodc5GsUWGxDktX0unIO8aZKPEg7j72rUW0VlXaPsmYUBLdJ26R
  template:
    metadata:
      name: openbao-snapshot-gcs
      namespace: openbao
    type: Opaque
