---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgBCmu8TSofIFcb27bSBoDugDJfS/x2yDTSmtoNmISiz9nvsWrmaJF7fBWbhc3nQpZ4mv8wouDTbPB9Mwtzqf6/ziS2yuVnqc1tWpc/WoDnowwDzRcmYBNnUZROaAOFaauG5AnsjG/HEouawk68M07cYnIcbgh/TPyQV2qr2J+e+MVOlLFJz0nkz+xEPC5mdoRJwB2P0HvNhUG3Von5iuHjVWJB1gjqq1WPE9Mi/q6BIXYx97U6677P2iPdAgSBgwta20lZi46DqL0kJd9mtWB2DjeOe3wuT8YS35JODhWY3C4b1To7gXVxTeqUUcaomr2GuaRu7CXbqK0xxcduKtLwJIISv3+qHzWE5L/vtZo8/FqfMiCwNJsJqH+q40nF+RpP3E1mEo840OkhN2n4arQ07WBd3eqUhU/Zf/CRinehNsMjBXusEbmdngl4x87gelnq70Ijgi/r3POZe2/Hz/wkVF1Vua+QTQbJ+UmIRC7F2RXmV++3eEvbgw76qIF4GEUo6siJTwrL3LFu0d8GYy6Y8pg3oVklN95+3kasDAfeMJb7xRTl+izJkuUUShZJFlRHts14Cc/2KEunGt8G768uYPDeFy/Fft+Xx33COhN2X5e9iWbuC6sKCCfm6YgqSZV0n3KnA0kyiiZhDfCH0L5OIMe7f8ogCvpEaGMkWDE1wBz++OwNp7opOYHWqjGb9GzHTk9wGvNYUiI91s0TTDtIzmbA66w==
    username: AgAfHKgDSge2EoWaoz83XoRiYX725R+Q1VybubJ8EAZcjYeqpb2h50KBw8wTCnVpnTvCWus8UeBDGxEguldXXM80phguT7rFGE6cdAAEgtEiAqHaJrtG/qYQT8bhyZ4syLKdXcXF2Ikl99AH+mJG6vRh7I2D1TRd7i/LRf/vk7F7sC3L5Sd+HHpILA+ebbnS002cRgvWTw8MYI6u9rFTgRjZG5RSR4PqKb4X37pTiRIcmA2V9BeQrIQ50/myn88J8KFznX66I/eZ+jDsGt2njmWv6aZSo/vOI6kV77lqOZoxi4AlQlYJpTkK9yJytcCWdMYo7Ms7H1ngQqTD13BGpl7poA74O+r0PIToqYapTC5+NyytFEyR/Dacj6TNHsWb5ryMnoGs937hOdSKia4yiHxnYFR/vQyrOB2Na8IhKJAR4GBtmkZWKuLJKuL9hblO6LQv3t0bfzkIiLW0Hq/RAogsBL7W2V3I8VGBDIkRUuTi3kPxNrSDSzYAwwE/WHBcwzr6L+W3cGWtyxc5v6HbAlxix+nR2sQscp3CBNxdPc6a8+KQNyOmIwpytL/QWshYfIB6JjZ9Ga3CH/8bCu1z9Q145I46AB3C24i3pnunDcJvWbDWuMepgQjYF8AgLagVcqYUYIPtCG+98R61CHKZc2OA3D28WEnWDRDK/Ojct9DeUFfKkIClxWrXGxjIOdVVmSo2mXV0mKRB97c=
  template:
    metadata:
      name: authentik-postgres-credentials
      namespace: authentik
    type: kubernetes.io/basic-auth
