apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-cluster.yaml
  - pvc.yaml
  - deployment.yaml
  - service-http.yaml
  - service-ssh.yaml
  - certificate.yaml
  - ingress-route.yaml
  - ingress-route-tcp.yaml
