---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBkzX3kiDugI+YQ1xfrVr8m9W/hRbr68VYZExJVvTyMJis8Ns3FDFIsu3vCgHsplgZ9WKIMoKqm0cCI0yQSbxiUVSUAZNuHWLazu+Gq5MOXbZsF+VeTpZUUdHGevp5QBeRUt8uDhdY674aHx3VIABmk8XUfd5W5su1pUH5h1DKbdXBIJJEDeUDTRdOnzHBOiD9kwMd2cJPj5eYPFOPh3wLF0uP+ompinFJrojP6Vlzyhy1E0ZEtmz1LHJQop/KMshrSC2CTcEU0kqbqDUDOHUOgY5AetBBo78LJdKZT1Gp2i6F4LIw0q/xUV1PYG0INvbP1oDkuiLStXBXqgb74JOEOOzkIkAxZJEtYr4FCG5xfVOHYZCuCgsUOWJ+HSuBvTaaSymihFL2NImJEu3lkT+VeroLMz87+//5TXA+2VSHGSnzHyI233zF0FQEoTJszlMGVeFDqp9P4H9/lQO4sLb4oVXVR0xiynMuPbxRqwlpijmlkaWcqtzuo2jbW/bBd9vn+LnZh0mpbCER09n5vDVss2hiAr6MS2AV5rIQgqIaAk0RbF+0dottgN3nKEqVp2CihWfAJwyC0uS32zSmn+X9CX6invd+4dCp840Q+VW2cc0EQ5qvzRQVMawGJ+28VdopadlW+YLQDfHif4rz17MlBPxziyxrueAX9bYsIdSb9dMvX+ZIQQ3CT6HH3c8Vn0thrNl6Gr5UeG8S+cggDs/xB5RD/5huQyGe5k3bkmsnZ1rkVO4dVZXIxsqqRxgmdCAYDpGTgNA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
