---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgBHGL7acp9/ik2VWYt8WG3+/DbLa+oTY6y5lRpa5U7Bcw55pgP2oOmttVGA4CKrxOsNEubiT0uHzkOWXA+lGGjljtEq5jbXRjHxAPd0qSciXXxvp2fWJxaAMog75XJVVIDb18MxKyQM6nSDLFtI/iOSS8dhNi5ZarvIMus3iio/qnQnf+GukED5dV56qU9HCGns6IZwWhLnTN9Pprk3UzbSr57a2l9y0xJyR2gcRvCoAH6cAdmMsm3c/G2uKIY2c9O1FFBuW+iR2kp5gfG3/h39V7lBMr9kHbLI1Ob8tBQ90qEDAaHlhS+rzrINTd7u5FhVp8Wkcmye8/6YUG/+3+JO+hAucSq4HS1xxsQS1WV6FlsNzovoPaya/fzGyvbPu5GDh8/zA7LjQxOrIs/xVHCY2dNmIBzWW0NxyJOlLIvSddw7KfcCPN8Bhv5Yx7oW0u5tmv/dD+rdflXBAJV+EBj8tKF3C4eiwHRKTX/9QXe9wpj1ZxA9q2/j/NVoW4Fozc2HdyZWh2JuBuULZbtqgB1GdJ0lfX6/uXRjVHKKfntT9z2Swk8tTT76vlJ0W1FFTRpa8KKfbKa4hxNUksqjvyfE5uIwaBcBo7AB9kc0FQ85ZMvGwgn/iWCUNAbv92CT1w+j1ILBgGRn9O+Vkz/RQcImv59SiM+yDxoDWkYGKNo7ZEC32o8ZKF+g7KekHCJU4X5b2Z6G46a5onGIgQyLDy43Dpbdl8ZrDl6gJnajGbfCzQ==
    username: AgAxV/0oYAkixPoJpQlrp9SJceqIIUgLc+Egdqm3CuboddD0vqIjma2PbqL8okg+CptoUQSFKPdsy7fFlepOMRRBBTUDZV/LmNvkf1ey8kseAu23qG5FP9DV800TAl2aWC9I8xgXvHtEhGTpV4oveM90AtvSt//TrRNWt/QZ/Ld2qHhP1BC/x0JeNtwo7LCTe8Viwnoq3kuQzrg4pzShlg0cBUA7Nl1E1s4ZZ/araenTFZ1mgZnAiUPRbLwnpveGG64u7V+fkVyBfcdKpguSYJENLxuqtjtD0evQjyikqjPmbMgrOT0h0mMAlRukYTfvQD0jIHE3z7CpuVIKSSKpVJ5Z4PzWpTuYTin0iaMvpQWF2mqDSD1cfFbvHUWQQVHqMTFADjJXlgJRDsmfGMK8TKBSGzfc6e+4wg4IDfohVfCx5g9+14NUga6mBEAWe2vaCZ9/Wd35Le2/cdzhncSZqYWu8BMbn6Qqt/r2aBkBXa7VMJV/W1ngdhQqfgUioV8/bzL7Dzg0JEKYfH5dKgpZevttDSjqYHPtS78g0QIPhy6YKs03EmWmzEUHPivQB9M1Ku+7lnX38FExcMs2jqQrPOW4dwCHg3JNz9ufRWv5IWRwbgVz47oGEF/8tYUTpk98/Iu+EyZgpTBl7G7QdRDG3373Vvy9ug7m9QQUyv9ImMkyQLgUv7oHH/gIpgE97zYh8ZauVBizCVApCwVUT5Ip
  template:
    metadata:
      name: forgejo-admin
      namespace: forgejo
    type: Opaque
