apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - grafana-httproute.yaml
  - grafana-oidc.sealed.yaml
  - grafana-admin.sealed.yaml
  - dashboard-talos-nodes.yaml
  - dashboard-argocd.yaml
  - dashboard-ressources-cluster.yaml
  - dashboard-ressources-namespaces.yaml
  - dashboard-ressources-workloads.yaml
  - dashboard-ressources-pods.yaml
  - dashboard-ressources-volumes.yaml
  - servicemonitors-argocd.yaml
