---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgArAXYyMIchNxFfjg26Ru7T+MER8RJEx1cexVddcr3dBBJ82bpr5mGZy80hxF3jjI5B+FDg8W0qpt5uJX2Q/8lkCqgzOlE6yXXBOHAlTqvi6Z6iG9/geGIFB+gWwJJHZXCEt20xLDaNGKhR169vFcaYc59faDWH196FkRDln4JxXab41GImcTlJA4ZL7BWIZyP452kN+YEIWxgfG13GVFi3wYz12cBuz1/imJATsP+IAd7XCh4nA2x3CeEX0KJOEdbozYlbO0cE+kGxRL0f7cOGkn31moDUrZ+0C3tZ7F2oH2xBK/e8CyDmV5eyrtDIlx6XGTEnJLig8nTRg+bWSJDfcSc1za0RMkGAdTDWZvdhF0znSAdZNlHjHi62LYRedgHTfEaBkWUeaJADtvlLvWD97oo9kaGmNehdS+boEa3+8bsvg4jRBiObRSMq7sjNFCZFz/P+KG/WriBk2PAEc31hptD1gcDCUajIe4Vd58UYRshaB87FgAOoXxmS9oh92pGt0Ql7pG+SZSeQip9Iry0VPcjOdLuoW7/DCkGPkCtP+1zeXYxQhruI6ys1/CdtP4WoUkKq+URfJmKyIIf77go13vjXwnjaGiOCxbzfXuKqZsExEbfB94dlsBUltoKVx/CSPm/EeYa4FSWtaiY5H60iuUnOYm8d9CgK89resdtJlhFo5GuPQb62wksEveRQLBrF7tth/5/0sVUBCO98mtunou0JP+CypU6+Vwa/ncsaOQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd
    type: Opaque
