---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgAus2itVrqAwESdjP/IXoh5AEi3gHahbgKv+9C0mwvk2KbOkNg4rnWnFvUSWGFT0IfC9gVJ+Bnk0ywiDJFYRWRDKFo+IFyYkoKKxWOue2nQ78FNLoNmXQ+mBoYZ/SrBrFCVLwSOyRB3EcpXgi7ghVqqt9jKO9z3T+4jcx95tzst8JZKIfqNgwQKF+ofHd9fJwNpuflKk0DaiUVA+6MNs9Iq8TQr+A/vmLbPAD1Iw+pcN0+c+JpSr5Z5++YgwuXWEa+jf9aE91uAkaqZ7E3vy0/5ai0IhxMG1/6UUGhCyoMudCnxQ1q/FUCD+dRiO2C71T4/0N+t9+zFoM05T4SY7LSYQauG0CTLSHoN0ubD24MLT1126Ur3XpnQbQC7XxBLeaDDRIPUajHDE7tsUj2HJziu5PMhYZBsL6vT4CNFsHtwC5IYrr9UI+e5wtMjtA3lVyOEhMsMjqq5KQODD2EbOplxR1A2GWRjcpYaZg2fzkn8vHLn8lmOb+lH6bijTZd5f3CckvUXkBi6RLTcDGj3bdF10luM66tbxAA6YsFU0/fmtxwYw1f8f1YYqZrLY9THWcNy39MwiQuIpRkeKn9VoJdrQQuCmrfsZkJCtRhZN4IemYXlz7ozYfYE0Wb72qGkznifz34xA6T+u1qE7MAkphSYHyaAWkdnmLFzLjA+P1IIycrEKmMsiKbOyJ24oaqciPMJxQsEhfJUyHeQizFW87bLiweIpniPOH0shB+pLFoEhAIG6VEvm8/tWzZdw3j9G3k=
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd
    type: Opaque
