apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-close
  namespace: argocd
  labels:
    app.kubernetes.io/name: hermes-close
    app.kubernetes.io/part-of: homelab-gitops
    app.kubernetes.io/component: agent
spec:
  project: default
  source:
    repoURL: https://github.com/jbwittner/homelab_gitops.git
    targetRevision: main
    path: cluster/app/hermes-close/manifests
  destination:
    name: bleu-kalecgos
    namespace: hermes-close
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
