---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBolrKw1JyCwcXqoJltuWBZkuWAHwcAn0JNmedm/6fBbG75vGVMdreyqHlXS9KqUGsxF9OwMFna/bcsvY0ARPVsqk0g7K3egY6OZHaS4HhWSB5qF4ef4GgzkhNEBYDZ/aPQHbi3PqhBykrtjP39a4Krk/GFPEdBgS8Bt6CffAZ7+i3MrZIrJvFYSvbtv4MaxzdYztE7MqqJmlgmzT7xF7aoXNskqOP9p0lpdzRkoXjHxwkizceUdJzwivYERRlPo560/HTQxHJhwgeZOZBVyUoxqMS1+e2vq5bMgD2WaACSoYMghV4DXu2b5imhZ6uNOX+MV2jt1C+9bpoLYC8FZEv1Sq9a4ooNB7pQn7QZwrGv9WFlPvDfjQaDLKfKls/aA9Ys6DBpm0oK11U08a8aa11kKkavK/qJlxRAecDW+wey6IQzuKzLmvRCR0YdnsAR6NsE8eeJLMCqSgGWqdtKL9C2ydjV7pYHOErxCTbo685bdsrWz3BuJjCTR6GOlD971tPoNmOxJru8CiTD45ok/lWe7v4qMqNWr8ineY/5qQIXRrxSBBqO5SaAZps6mgJ1w0Z11iEXqtEw4PwZd/bgp8iBCvybMSlD3XECa8QO+i+NjZsOQO22dnug3n9T5z2e/2Z4sC4JpEQzl47Mu/CNQYlMn1l3jDuClIrWyp2Lh0jXJQ8t8BEjf+tJQ/tIE7V6JstTcVT1Ka6Mtzc=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
