---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBusqrCpGFDVPtGrBswLhk7CLvtqOe2Lyn1lwB7lg0l1ljNwN+KcJ0ngLfijGzuLRUtW0XeYH2qvV4YeVkJj+Sw/EhVBK1igv5MdlhpyTUOdkklMzumHKnm4dSezQgf3GTCkAkB/jIt+WBqMgEJVtgSLQVVYf4Mq/bsDIPWxhnA8RPkzQtxBdy7o9Uw7XopoA0CsU6L10ou856lVQSTHpAuzfkwx+EyGGrZ3aAFEicUi4QI7+dZaSgdy77FAftkbod760OKeYdEtANU6TfvZy5MEFtTYnCutv/zP516H3HpHpEusqyvZwKO4PkofEkw27kAtC9h2leXnTOV88CNkQyT7uWAcdBvQuqIwSiAdFzV4o/l8F6mj9BuauhUcOgG2xGNlfcL3jmj+Ec2MANFagDF/r2ihkg74DTiO3H1HHZRSv8F80dLsnVP4gifGuFJ2DfHGT6QoFXHQmOWxeO/XGHvb4DESQ76HBFwGqSeauH9p1qF5nO1zvS4KvZ9Yy4IK+uCLeTFm+h2AIwVV1KQvzxrVwtogcwdoDMmxY03z8oA667fydgJkwJIbqV1Lrt0gUx6pElRoBRomNmyXkLacsBiOur/FUt+hZfU/oWDoS9j/k9UYXclQW+J9sApAQefHe3hHLS/Mqyl+b72u2XxpGjVGZmUig8ibudEY5hmx7wWS295E37PvRQFPpUWKRt+yx1280rrJcu8fcAoi+esL2PmOiidW5PgYGGTviV2+Vuw5sMUF+/20auJ
  template:
    metadata:
      name: renovate-github-env
      namespace: renovate
    type: Opaque
