---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-forgejo-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBf1VRO7Qz7gyfSfuvTl0fPk7TtrJoJGPgauBxymfUX+BeX9HGt+e8otJon/8wD0qr9ukS/CVlPQM/9HpRDLwiRbAa+GEqy9J03ccZRO2+eQ0UVVDeLUXfBlg/eRFnWt5XIS68K3j7K0xa3Cbv8xfEmzZA8ZwjDAbMATXJSeiHVvFhDnLX0I5tTs42EG08YLXlSR9XByfmPh9g1+vw+PWo/dqlxzQTqF+R0SJ+Qwm4Vo3AcY0F16q5Im4TXQJHDhjUjX+CXajAVthJx68zEowkkDE4u2YblpAGPAm7YXRnkigV08X8xWeGOKc7gZ37AY7ObJxAmk9PcleIL3liWpIGkMPxUcfqEH9NeHrT16y59K7T2wF6hBneR+JT92iLy5gb51dovB9zUPXNjL3tdnIX0p7x84WxONEPXUDT4O//IbBZ4ZppmORjTJZZJbEe4nkxuasrCrmhkzeA4m0emNSqYCXn+IAnl0NGt9MYgf1pTF+zyRAwom5qmXxSKdC7S4Zl4CLG9wnxCrx2Rq+7jzLdHoKrYa6n4+Q3tyU3OXAMjtqbCYUZf0QPzoloQ3ltaUjIZQ7IbY4cuDGavwH7L5cQlUO+mMmw0pvTfE8xKDaMsO1U74cnOtFy38m56dueyS0monhVBpi8yw1a/J3hZczbtxIk4rR0NIc8axYcXYF+V/SXQqiCQM6F7Hir1ALAD1koGc8Uwk+uot3YA8kqjLgcPSJ7qPGseXTZTG7JOqxQ=
  template:
    metadata:
      name: renovate-forgejo-env
      namespace: renovate
    type: Opaque
