---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBx8NAK97RCqMMTSW5WZ6yUgUYi04MQtYSAnUWuP1u14olYPcspNUNFs+pvIE3o37h8dmpBgZ7Ra8Dp8AXhgVAnTNdBh+S52F6lkIQO+KJ3OsiM23dR/98DupBz09QxeIigXE64EdB6hHwet1KwY9dTyMfBeKr1HxS3oCqV6D4tyQKToM6daxpabw2kRFvS51hTSshOfNmauq7lqGzEi/xruzpiwZnLuzbEuYMfoyEHYALuNmlYwjdfU9URnyY7kUbY8Xhoco0+c3Hq0tOOihqt3yOEzxa7eKYItB13JtNz/SOfTqxAoynurXO3M6k3fVU73HSosTH0je0VQBgl/8z6Q/UAtXR4dTrO+gt67yX2D0/wG+va+sPqAXzcG701oIBZ1+QtEZ11XkA4EnXHVWKDpKWeIMMl4Gx5+FZL1ZikhG1Foov0M7vj1EuCOs30H8GrWHI+wHYukGsl7ljSQbSU7LkYZP3enm1yTMoSkpu66aDk/FOqSvZvHPH9+YpD2+MMXgktwGztwHLF8bx4SgYQkdA/CjSf7rzCauDBiF1t1asRHF46ToC409NJojYTImJh40gGmcIy8ZR11eboOVCD2apGxgGBCoVrDffHQWJ7qSi8FlEeBPcesofAT6wDizxQYyorasvFVtzPMIH0MwHef5xnfJbIIYWK1AVoaqSh8amkpsYZ4rHbluuSkhpnHFaayDv4UW87C0+xihp97UgslMkzIhdG7jvQJEpx4EEwqQepWMZftnmZnL4tAcH5tYrNMR3P+VUHPk9YFb8FsOn9iacrj/spwKgtQui44kZjLigDrSdYP0BdxU/F9Uw=
  template:
    metadata:
      name: renovate-github-env
      namespace: renovate
    type: Opaque
