---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-forgejo-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgCQbWXaPNHpNbwDV6yuuM+MCv05YdU1I6O2u48gF7By3r71tHOEn8xJ9JfO08e1iRS+ouetK9hHoad88qpOjqPNq+5UsGflSwoqGITKtgH/nsa2Jf9l9iqq8ePUiXjsmtBAipgHEdbvNZh4jiXxJlYLBBHXKA9BCb4YBlSEki7+0ZskMGE0imJqIJcyD1tLgpVtfzxb7c3Q2XT46vQccif9iXC1mkvhokH2RUkZAS0kJJsBm/K/xVYJx9QBwAQFYLP2MAoADB7H9EJN4zUVrqnqmPMgKIHASWt09Cbl0PfIFOr6RLNRrF7R8ZdFYMvAioFd9C+RntSjJYml+OHI1ipiyQwxo8yMGFFyu7BfLSW5pEOaANAMUR6Y/5uyDhX3AQ0Vm0NF6el/RlnCUR+fhw1444Lb3J55hV0BkgJ0JQLcuuHWQoDr6fnS88Fjixli+fAfbPd0qojHDPmRmqTT4wvu2+VnTKPqpxSKI+P32nbG8plJexEjCGTAwNAC30+DX1Sk2MQBICqubqiXwtfs7gSI1kVi9IEh99Ziq6sQ/ZGyX85fjd9S0/TwjeD5fD7GbTH7SHZoRKS6vK62vuC3U9PkfCyWnLGgloXr6Z/mdot72IKkXokRDCecRiZ1/xIEysBswd3EtanMYVGljKXkDdEV7OYtCh6pBwP5Fd46r8E1hLvUeHC0hwUOEvm92HtBbBTxJK7Z+iCTqGOSV8SsDamXUb9EFQDIrtwR98lxkWcjpLxhYavkBgudKS3rNphtaTOgc4zgJ3Ipj7hqz6K+jQw7AbNz6jOXdylm9lhRSZIlIG81rKcXg4J7XaKOe8E=
    RENOVATE_TOKEN: AgBJIW/e8tahUmYgE4PI80yJ5uJblvXlaz9cp+s6V0JoihbvaG/k2W6xMi8jVQA4tQsjmCWpDiuVDkIioWgbH4omvgsDeO5EVJlJtXgdE1ySu0XmTvXqcWUy3I5YN/PKUtO03Lf/u7hGmKKsOTOGUCLO4BO+gxm3cCHH82ARoNh90nMDdiPfcDVvSv4fo19fWt4rVLNEzarK6xQ8YKAACkd793QVJb4cjIfxEgR5xHJNS2MxZwJCKxnXrtyJHUupS5Afl4zdfdVr/Vr7x1GBDMv8ANhvR/EiBapufTx1RQsj4wk5Dg60f8hmwLdk6SZJevq/YkcchDE3vQ0auPCCEt2nH6/k/OHlwq+Yf9hZVBc02D3a9VA0InQLXsAse9jVgtgaDcwteLgyM3xN/AGekvZAzXv6UVD9Byphy9Ld6tvWiUiBG4xIwpf5plJK8FBLRFulyLdqikWnnFD7B4IP/AAcQqjU7y4FW0Jcg0H7unMqLg9yymUh07PtHappU5Tz4oVVWxRgHEgXX1JdPY2JSAVl/PIYDqMwLZoRCwPX5NgMb1vhVi9dxSqglvuFctJUqw+DvarBlb139NEbeNqjF33kxr+xOnYBWCckf2MnD5zTFZhYnKl6G4yTm5M0VlfXylIm7X+mDTSZA3mVIxc1vEKwGbxVHMaSbSfv6qoDIRNKS/L4A9vNHQ9HObTIE5HF0BzxsM0JCikS10ESHu/QTuu3XVQ8WDVBjaQm9qIsfb4POBQOwM7uwF58
  template:
    metadata:
      name: renovate-forgejo-env
      namespace: renovate
    type: Opaque
