apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 1

  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
