services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.1
    container_name: tools_homepage
    restart: unless-stopped
    volumes:
      - ./config/settings.yaml:/app/config/settings.yaml:ro
      - ./config/bookmarks.yaml:/app/config/bookmarks.yaml:ro
      - ./config/services.yaml:/app/config/services.yaml:ro
      - ./config/widgets.yaml:/app/config/widgets.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
