---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgBnRID0ft9b+/67mqUo56uPX88B01zVSPuNJKEfN0Ga5XEIJ6+RXbkY/gfZtezT+S8yi9H64ma2boHs7RgrOtRTzAOtAjOJSWDFOzJq/rxhp3rq20DmjJA6xoJt7Gji4NEyh8xrLodKQm/JC4Ve1E24TC+uaUoykEY/YTm1Jtnh4gGPeZN5NCgjljnkN4td4bc3GXbEb4N8rn2ve/NAF7qNsDadFO6I/gQKqO1IzrjDxXbgEL4WceCE44j0yhxyd5B3765AIU2QGpIrDzVeRftmIh0u2Glb3ZpB0CF08zbXfsfuSHr+lv53yzLi+i3odc7XaAqWGyJUB5dbEVH9t9evvOM5xzWEcd9wdv48Eg5D2asO1jjxr/qDx9Ir+7ZN1V0j1ppUI0XNjdQDuO+NrVkNvAgiIfvOoHG319xTKz4cOV9NZ41S/wOR2EXBz3qOapWSipuTqJUUSmxXBMjt5C0vy09JZgphMWxUEZRjqlHw+wL8lM8Rv30iNqfVCYjXtZTQqNoOePcjyU0dUGzFN4eVcNVm3oyotHGsUqFkSru8OEqfHXwAFPf/gsnme37P4TkPGU2/8TTKPBKZd233YU0XFXEqyuJCF34PEDNd3z4P29tqk0Ceb6UL8CLF0M85Ot5EA5hVEW7lS7YrkjPVFJzGgtJaWHeMgzo11Ql2cT1jZtUs44+le6UDhttMQVk3NUvMXQ9JHCH84VpLawXNsdyoe5/aLyaWlubvOgyiP5NSTwEcULdaWZP7dicxtwm4yhXbh9I2Yq696FA4SPo6/jQo9ZjrkjJBGNWh5EVcHBerkw==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
