---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBY0apwdN0b0+fZX2Dw31TD4iz5I69QXE6bDQVcIAUAz9h/uio0C0HJUecax9CCliC5diQc4wVIFUs5tHwUHB4DnrD/ukvWKeD+LQtdg0TRwg7cdZ1zzNUshB7sTbNr5OmLs6ICQjVxxEn173zew07D1kfiSgkX+QvJ1qvsihdhtT4aCc1a4R5S5KXMb4RZnXYOVqeOIn9UbO9tHb9LES7w92vHymNMKUt8hvZ/ye0i9570IkHL+eohS5A4Q5o0D8w8FzrQaWxyIzLHBUg91hh/jSva/epwSWj7jwySHOYjwlMFjfxKHBDlK5XuilQfryrdmS2xkUx941Me+XfzmOnk4x9R8C9a4UegV13uws6kZCw+yol8puira+NoTPsEsCUIC0w1nH5DHwtCVXWxhapkDN/UBpfogpzZrz9m+CXiENjVmfR24fBWv7i6wkDdFDrRDNZM/hN+zMYvC4N+aqhmpj576t83TjNPFqsPtvH4AcQMtit1eSsc7iEPhckLJkrxFk41O3VZn1tA/tbpYB52Dhze52TLwX2nxGUGyX1uimPnf6iDsI5r1id2YIJEhHYGMlgLJbOcDx1qtlPeMHq7iMUhcfuKAv6e+UGqVQWwnaEHnqDECuxkWgfkV79sVE6z+tz6TTvzWe0XfzRRWbENMhutZaUTNL9jnQEbu1YEcKQWQ9VrSVYtO5iuljsig7HpO+qv7wI3rJEMQIeP/fUPlOyz+nianBgIfogrHm/QKw==
    admin-user: AgA0IU6v0uz4gJ5Uf3zvNEyHcBjfBLqQBukiz7LlWbOyLTgVQXPskCadMxGK1bDzqm4e24L8FJhKRdbWzosN3AJrX/xnZm/vQii3AdZz+PNfKS6sJHVmrZ8UHuauNjOk9Kz61/JtSsOnsPw7qubOKI9yIzqs9EeuEgMvFhiUDuxo5BD3hmX+Yu7PszWJV1eIU1jGoG0xiwlw1eW1Wi8nMkdgYX8AmdwVWK3cIZLKwx941X+qvFyerAIs3hmHlwOIuUwBWWgwhVkf9WoxA+f1GqIXuuXuI1RaFNsIwurwdG1dZevLhaQPRQ8RdGmksisS6XGgSa6bXT54mzbn0LslhES/qW3m4MDYFEfu6Y7C22KFM5WAQ/sWNxK7T0qY2UAjruqZiopNuJ7SdBsBgrSFy0lE+Ze6nWek7WJHpKhG/bk/mEpp90TQiLZZVDmynZloQwechj2UMGu1KE+LntzJkIUBmtSKtwPZ9HyEUWFSFLpQ0aqlnJhX1RBiNxGNF0lf/KIYsEiJFH6y5FCfRw7j2V+sNpZ8kNnbcbRu3QocoLHlir2K7rYz9fXnnZCMC8AJ4lp5AbGEdowh/wnxkks4245PWOVsqQhjZkmc6oyzCIBaNxdZSDA7Sh51KaV9o0aJs/JXnJI6i4ko00HGTct2iy+PNWSWANpVFjg8ux34fbqIYxw92CTvepY/xdx8pNGDXrT9akwAPA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
