---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgAkvci0P5IQH6ezqTvfSxFg6AjzusxJdgUkVPZjkWq+lcNQJtFHN9TNmOKMxHQN2T5Hn1XcWpXgTTkOM8QQaiXnnQAnNBj1mUnUaIzQhIDh9NLH0BbxU8dallx4+fSS62EB0H6Oxof7Rb+wV1GfYriKgh28qeT4XQCdObTten6ZvwsBde7oiBLC5DTpCxOMfINelB/HB+GM3kCzhEV3zEW475kE/ciDmlzHK7rQkkNy8zNuXddqUCQHLvmJvtiPL1hUy9f/E1q0JiQsgCr8gxLEE/GcWKiFjFWq9Z1d037rZYbPRb6majPPV+yVAS3jOBTzphLrOWX523z1rPeTvHaDAM1KrY/5pDqHNjy1mIvx6OBdSGIk7e9EaGci+WI+NjOP4KXSTfELK9BPBAXvTTHORA7pf/9KUdYtw6rK6+vuGf9PIRgTQM1FFApfvneRnAy85i0xSVTfObECu+wG1l9KZnDXTqojfDkZY/UFDWyTcjWFsJcEKdZJBNiQv1Kgf5YWaOQzzh5ifNucV4EQTHfIj7MPfYL+LSI5IAYTezyyvrDzpKR1d9j22nwTLU6UeeL4ttRI7QewAUcNPLkBFEgkt6GtzlQcCrvsO230VDu328m3k5ClYPZ9E4MUxDQjh48Rm0zYIeV6nhEDfjeBAop6U2Feu2b2X1VaDvC4XRrzuIGzZ8v7KRl8ofGtZYO+yFuC0yuYNrQlat+y0pmBRg2mnpoFttxwDIgmzRCmcSZ8nw==
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
