---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  encryptedData:
    client-secret: AgAwTAyocQgar0TeIbVReKFQOXdv6WOnWqa06pJusxe9HyjGHY52E2BdfmSvs8eXj5nim2iIsSfvkfnvZKonxXe+7t8uoqbURawvXjxeCUKNQkCdhraRSyuqR4JvC/+YIy2koYnSitqT06pnJUB5fhSrznnmGmKgJeh3Audwgvkg8lW1iGhjM+cNnBDL0tWBFR1YUxoK7AB+zYdbiRPNvqSRpOOtjbSKUQLQl+b0LA8vPobOlLs+4Ska8jgqVb3rxGthOLf0vNfMCrNv74Z7mJ+swAkbLxKVIPhu5qITdjnKP4l3oOOSCIex3Cha+rFgA7+z4JeXUbt1kDntOcyhpAPsEaWf8Vs9ayardcWpEXz4Z7uU5uc0ZbatJ9bXm3twTJQ+r06PiJATS1HQqWYjH1rtlFhmxIHc8xrR1zDay+n5smnHORgprWYSZFrCZSQ93NjaoY9rX91E+9sUW6eWr10jSm6L155ePnxm/UUTOI+wwOcLv3a099Z+h6BywCmwOEygfkq+FhqE8nj01cLyor+FeYs2rQLOsNSyNVkHWf/tzOFJziXLtM5K8ZYDLGasokron1ecAaxLE2uo2fx5fPa5y7O8k5Ehxn+F6gMhlCxNbgvRJfQQjNXmwqfpaFTksbdKnP3t+c6OhGNBKFbZeTW0gJGn5R7DpMVkGKslL/sGlpEnA7q9HWjCxlN0+vfmaKZ0O9QoezINWpaCy+V1gN2PM0bXxQtDqKQMVAO8XCyg6BU=
  template:
    metadata:
      name: grafana-oidc
      namespace: monitoring
    type: Opaque
