---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAwcPOEgge6Hvy5aDqtbXlkY5CmnKFYL9HVv3drmVBCo7EkmiKSltdeTTndYIkhSvCP39zj7eV4OApCvnhvWVs8UcpL/ach/d+vI3jbMeaEXF8ksE0Wzx2i9Rm+2stj8vu4+ozasmKckE3gBFMye6sENXMnOUmfD9tya/TbJwFV2OT84789kCQrh509NUYLy/yh2a8rmJd7UIHPQxj3ztTUADoanLe++xgT6qKQiXm+LoG+e6Ewq1XiC4mc5fan2Oso+Enfijz9NKDQuG2mgzMpNwy/ahoYNUcZrFbz0TeJxaMNZLVCFiX8y+adMh7pPxHGWfKBcSrk82q0eCUcUFtyBYFcp5YpU6+Z91llVLgfVLDNpQuURW04aG1zAh0Pq95Ueii10JawlkevyQyJGOPp9tY7KUYjDZb5gH5mOVB/hncVUK9lSx/oO42kUkCX19ml/sOOPiP3IWVbRS+U8Kzfl8S62sMzVoqRjXz8jP5dtN9b3WNww80fcTwHT9YhKX2YgAU+VyRLpTxSBamBnnumuswwdbfZoyeclG867t9vJZAOexJ+xUaaI2dPOB+K3a9jdbUtxsgZgHpLo6NgHjMMpZ9MMw5ienbnYixFecDv2k9RmlW4tPfHEaK2E8iZn03HegSvlmHLA04l/TLFNQXahM1yRwJEf0bzgS+LGeG1UKV8DAD/CGd4/rf/WCcMf/QBHmI3O+QsBROqh0apXiC9ThGsz6ruMzTZ04nhvJI+uA==
    admin-user: AgC/3e8Q7d3B23PZJm7NrTFiqFGKbuP2d0CRZku1Z0nPdPDTmBOqkbhg5aCyiKDqQDWBG9fFWKulkIyK1p83rBKk9rYw9kpzDUa+Bstmtw/8EsK9DHaz133+pQCgAa05OCEWbmiC5hxtqweGPgVUJP1tTVhGgn5sW+er9IR9z3urn4AHlXZXJ4mi8SjnqjvWCLXJpNVpW+HTlvkPYfUsliggs2zEULFC6+u4WhQe51MkILaDKMn+HqhAy1xBttAEdOtbEqXAv7XgBlxCzRMyMF7qrdhdS5uOYtmjr4cVlpUSkh6Rhd8wSzUP40729IdxhK3hF5tsjnslrW4HvP/zPQAj5Qm2ywPeZbvRNYPJ/jZF940nvWGJMGw6q8pQurAmKbxKGNuCmXHoVDLNDwqsPhD3IE3aeITjTRqlrpYvMAXpqKlCmUs8Xnw2PMxLCgGODFD8pK/ZfbavvOCHvAu66HyD7Uxs6n5YAOfKHyI223cBgORvlL+QM0cXj5Zq/apJGbZH3UUm5sEZfvv2E3d1Cp9ASo8/vgQ5L9WFYEgtXY2pDfrps86jVIJTapWmr7alahFT7gqTmJo2952WKRgNtPdyymg0PBKKgM+1DJPZNlfVo2byrJx1St0SBy2RLnOm41RvBHt3SU8dPF2NP4tuM+ncKUv9yHa0rhwt/ZBkrW5w1fSzz9pIyIkXSdPtitjFYGN7ZNrVhg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
