---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgApgvPxrO1fl0FfwtLI6QBktsrD7MAfIQViXsKAm36TjNc8VprzTqea1pP+wwmznoWX/Bm2kaeBCqanaomipRxcBBfrT1EdJHzhlQN41fP/PZuy2L+uOqiGlh6j7Bj3Vo1LXr1+8ebvPCXHwCR/3Ko3zJ6Co2nFcw6YGioO/kwpDg1C+0tabkMVWiBiG+81JQ05QlLE78SqG/qfVN98tQwrjL5jgfJEote4SdiZe9SuB/mRSl9yiRZAIrQmFEDdakl5D+rZbiyC4NfDB7JBHQ08rTw28+w3+0dxcTqm+NTFWki873kUehAQ4ow/ilKCf9o24SF9RY8m/NCOumNGwU5B5rBxdgrKIpbsSB/WbAtBRlFe6dVhhRMQv4rnl5i7hih+WM4mz59+7MvBF+D/+Icu5PTRqy1jgoRPsAKd/ybfqQIhgK6TvHcSj9IAsct6wCKdvmKd5VnnroG8DwV1JGroMFfIB3f0ucVwPH2Ob6imxikGacHsCezbh/aklkFIBvH7wZSc2v+Nl9f4Opwzx4GPk0i5+4mNPYZs68YcsGZs2Ijmz0KFbhVGTQSWwd7DwiEFvEe9PnXyBszMCPwfr0ghcY0FLdqP+wS/cx8dM2Snv2qMS953FTLXgmhqGBBV0IFIopS7LsEv6jP84NCkkLtXxdATqVRM49d47dL3fWcJbH8hYS2B9rGru3Rh+bKyf6yH4RnXMP61C6nkZx2yOvOPZ/NSDpu/ICZA5Rmk7ZJA8w==
    admin-user: AgAin00s5dzoh0vC0YU++arcwG+LvwfUr9e8UY971CIlwj7oH9vGbNlkeNIqzcNOsXgxovOXTdzAA9Ui7h6nHLPmbhSQAIr8w05ZzwFASpiXPA3CTcj5dDPc8wFUfhz/tYTivDFrUw1aohcro5F1/oxz6PmyfajRpftoheZLKsSmLUMCWsqR7txfm9c3oHnslirk6Tb+uVx+kLPWcuqAGoBzbcxHLpKVDZQoamKQFKlaShgp2AULxD5xmas5jp5qW6HS/DizHOK1QGGC1jkgDXe1YIKhh5whCWdcnOD9ci0OFtoxHHvowryA0QUzAh+8gDKQWzDXdy7qGyibgdUoEepei0Tuz8Kd8ZcaQFM+wss3E5j9ap2+1wEeT5eVc8adyBl5pFcwT/sA27vg3Vsqw3FhWKpIldyhQ23vnRT/a2zzEuFinj8wBh8itLWIUdmylUa/ZCNuHRnDsm8F9WQ1J1YLE2E32I34Fz05mEQ38Q/v30cmo4e2Pyt9AjFdufKAzbhxoXMNs14qkGkcHdM2hggcetKVCwXjx1lafkRL4SHWpOoQUOvkiFC5mCjnAOazCOivqCdTu8KTK8BHEV0f+ws8zVyqKcpmNNqnLrfQjiWzwJSQsXyIvgqBsm8aB8tX6pcDayrNnm6qqfBaDl7RmTf65hLo7BSqZ+nRPLMN4LcmwFcQRjMFHsPOsEvxqkghY4tIjeWBBQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
