---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgB+qMKN1vxZ7aM2B4zmjyhvw1wxVff6nqHtiN7JR/j8NC64Z5GP3kCraePdaKAdgGISFS6uStzEga9NNl+PCvIS0hHjDx1dg9K74Av/fUtEH8J1sAHQXldRUs4oCXTDm8MFtyhiXhNnXO70ZeQIyf0lUaZaLdOux9tFeGEbH1zb7o+4NgwTOcfrSPZa77dfxE/UHGZZa2wpWur4X/e3OuUtjCvZ+MRhC+/et038pWuvVFm2orFvX97O6a5KfdP5GR9lBRL+f7xQb2hj/RaLQHLptZ3MrfWjckQDbpNFfH4f9qK7+Ftcen1MjLhshBMOdKK0DCLCVlO2RHzBCD4u+hA6i61EZNAml1DHN0WOoHyTsnVrQ2B5Ak5wo6GUbJwDTmNHH6dkAH70+JF35NWru32Vuixs4BCUr6VTsIoB/HOWwWLlVyoMTTifXc42770rwK0PtsIxEYi+v1m1veTOp5F0iQoUFEow5j1yNSCMc2yRE90iUn+sc6Q0N6f6h9LQRZZvPbMKLn+k/EeLRhqSnyCPXUXOTlwlU/xJzRpCj8/GJC+gPVk9EgjminvMgAXyBs35eHFy9+55gWXbCnFeNFezEAZhnQMQAOsmptWUo1V/A7DoHpni0Eh2G97Z9XDyWVa+VpTU95mQsbNspd5mhwfXXf3Ws0Gks5cc3DTQJnvhHSXwD0UC7NgHtXTtP7EE20LXPSFYEc03DgRpf4nF3N9pdXE8g/FitYJZIGvtL0ziWA==
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
