---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgCsRfD6T3URrXzBm1HefcJD3GqRSWd75nh/I0x2IIWuEhh00mvarDUT094mWYB4fPZJ2BC14mEfP+5dCxnmjwSUSnAgSUD+FqBHeOB01x8+LlGdOCPgu2mnDxCawjN3K03vi214hw3EPCWTEcGUfDF6OPzqpRpQmuruLri5TwT4IVC3VmBTjhH4XrWLPzPiZGoRdmHqifRLiv4JSnb5w8uiEqVT2qI681RPWC8zSzJg63LAXML4Sv8Ah+CDwcICmDFAQHBkydfelRE5Hz28Q4yHK6S1zBjZescyhIpF9W2e1wAHQ9oaHUjdQVbqpAQdKb3abhEe/9rAD4HpAvsDD3z+sdZc4Chw8yz9eKfLIc6d3YpeBJyH/+WjIbQ6g5J02JwEcbXHGk0RtqwCPMchS2B4hyT/VHauPR+EpncCKPqueKfXo1AgDFpN7xlUaFy9A5X9i3LxHxE95cUdCqDpNCWox5dcuMqItiEcDoi9GPGLJgpKJW26pG+YVQOJ5MOpIPJTWqYFZTZ0BqkZS4rRpJDrQ6+a9c6ZfGgT4kK+WBsjS8QfIdtm8nLCU7v+5CFGt694jgJlRu7l4ZZomtJol6Mce/7aBJic9uLNQ7ZnNMX9Azz5JL4vjFTaiuDFifg4glayqB9zqjTHSASEKQR3x3KO73uycBrfTaa14SzWSIzGZYqC017GZWxPXDDB7yB1TV9MJ5c0Opa4FI7/RDCiYWKBvQK4XqJ4lCtqb9U08E6G1w==
  template:
    metadata:
      name: argocd-webhook-secret
      namespace: argocd
    type: Opaque
